"""Dormant research-only Strategy Science recorder custody package."""

from .canonical import (
    CANONICALIZATION_VERSION,
    CanonicalizationError,
    canonical_json_v1,
    logical_id,
    owner_identity,
    recorder_identity,
    sha256_hex,
)
from .contract import (
    AUTHORITY,
    EXECUTION_AUTHORITY,
    REPAIRED_EXPORT_SCHEMA_VERSION,
    REPAIRED_SOURCE_CONTRACT,
    REPAIRED_SOURCE_CONTRACT_VERSION,
    RECORD_FAMILIES,
    RecorderContractError,
    parse_export_envelope,
    parse_export_envelope_v1,
    parse_export_envelope_v2,
)
from .coverage import CoverageReconciliationError, CoverageSummary, METRIC_IDS, derive_coverage
from .custody import (
    AcceptanceResult,
    FinalizationResult,
    RecorderConflictError,
    RecorderCustodyError,
    RecorderRecoveryError,
    SCIENCE_ELIGIBILITY_PROFILE,
    SCIENCE_ELIGIBILITY_RECORD_VERSION,
    SimulatedRecorderCrash,
    StrategyScienceRecorder,
    VerificationReport,
    science_eligibility_sha256,
)
from .outcomes import (
    OUTCOME_ATTACHMENT_CONTRACT,
    SCIENCE_OFFLINE_OUTCOME_PROFILE,
    outcome_linkage_sha256,
    outcome_series_binding_sha256,
    parse_outcome_attachment,
)


__all__ = [
    "AUTHORITY",
    "AcceptanceResult",
    "CANONICALIZATION_VERSION",
    "CanonicalizationError",
    "CoverageSummary",
    "CoverageReconciliationError",
    "EXECUTION_AUTHORITY",
    "FinalizationResult",
    "METRIC_IDS",
    "OUTCOME_ATTACHMENT_CONTRACT",
    "REPAIRED_EXPORT_SCHEMA_VERSION",
    "REPAIRED_SOURCE_CONTRACT",
    "REPAIRED_SOURCE_CONTRACT_VERSION",
    "RECORD_FAMILIES",
    "RecorderConflictError",
    "RecorderContractError",
    "RecorderCustodyError",
    "RecorderRecoveryError",
    "SCIENCE_OFFLINE_OUTCOME_PROFILE",
    "SCIENCE_ELIGIBILITY_PROFILE",
    "SCIENCE_ELIGIBILITY_RECORD_VERSION",
    "SimulatedRecorderCrash",
    "StrategyScienceRecorder",
    "VerificationReport",
    "canonical_json_v1",
    "derive_coverage",
    "logical_id",
    "outcome_linkage_sha256",
    "outcome_series_binding_sha256",
    "owner_identity",
    "recorder_identity",
    "parse_export_envelope",
    "parse_export_envelope_v1",
    "parse_export_envelope_v2",
    "parse_outcome_attachment",
    "sha256_hex",
    "science_eligibility_sha256",
]
